import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Plus, ReceiptText, Save, Trash2, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { useClientes } from "@/hooks/use-clientes";
import { useAtualizarComanda, useCancelarComanda, useRemoverItemComanda, useRemoverPagamento } from "@/hooks/use-comanda-acoes";
import { useComandas } from "@/hooks/use-operacao-leituras";
import { useAdicionarItemComanda, useAdicionarPagamento, useCriarComanda, useFecharComanda, useProdutos, type Comanda } from "@/hooks/use-operacao";
import { useServicos } from "@/hooks/use-servicos";
import { formatarMoeda } from "@/lib/formato";

export const Route = createFileRoute("/_authenticated/comandas")({ component: PaginaComandas, head: () => ({ meta: [{ title: "Atendimento e pagamento | Agenda do Salão" }] }) });

function PaginaComandas(){
  const {data:comandas=[],isLoading,isError}=useComandas(); const {data:clientes=[]}=useClientes(); const criar=useCriarComanda();
  const [clienteId,setClienteId]=useState(""); const [aberta,setAberta]=useState<Comanda|null>(null);
  async function nova(){if(!clienteId){toast.error("Escolha a cliente.");return;}try{const id=await criar.mutateAsync({clienteId});setClienteId("");setAberta({id} as Comanda);toast.success("Atendimento aberto.");}catch{toast.error("Não foi possível abrir o atendimento.");}}
  return <div className="space-y-5"><header><h1 className="font-display text-2xl">Atendimento e pagamento</h1><p className="text-sm text-muted-foreground">Tela contextual para finalizar serviços, vendas, descontos e pagamentos.</p></header>
    <div className="card-elegante space-y-3 p-4"><Label>Abrir atendimento avulso</Label><div className="flex gap-2"><Select value={clienteId} onValueChange={setClienteId}><SelectTrigger className="h-12 flex-1 rounded-xl"><SelectValue placeholder="Cliente"/></SelectTrigger><SelectContent>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select><Button className="h-12 rounded-xl" onClick={()=>void nova()} disabled={criar.isPending}><Plus className="size-4"/> Abrir</Button></div></div>
    {isLoading?<div className="card-elegante px-5 py-8 text-center text-sm text-muted-foreground">Carregando atendimentos...</div>:isError?<div className="card-elegante px-5 py-8 text-center text-sm text-destructive">Não foi possível carregar os atendimentos.</div>:comandas.length===0?<div className="card-elegante flex flex-col items-center gap-3 px-6 py-12 text-center"><ReceiptText className="size-8 text-muted-foreground"/><p className="text-sm text-muted-foreground">Nenhum atendimento financeiro registrado.</p></div>:<div className="space-y-2">{comandas.map(c=><button key={c.id} onClick={()=>setAberta(c)} className="card-elegante flex w-full items-center gap-3 px-4 py-3 text-left"><span className="min-w-0 flex-1"><span className="block font-medium">{c.clientes?.nome??"Cliente"}</span><span className="text-xs text-muted-foreground">{new Date(c.opened_at).toLocaleString("pt-BR")} · <span className="capitalize">{c.status}</span></span></span><strong>{formatarMoeda(Number(c.total))}</strong></button>)}</div>}
    <SheetComanda comanda={aberta} onOpenChange={v=>!v&&setAberta(null)}/>
  </div>;
}

function SheetComanda({comanda,onOpenChange}:{comanda:Comanda|null;onOpenChange:(v:boolean)=>void}){
  const {data:lista=[]}=useComandas(); const atual=lista.find(c=>c.id===comanda?.id)??comanda; const {data:servicos=[]}=useServicos(true); const {data:produtos=[]}=useProdutos();
  const addItem=useAdicionarItemComanda(); const addPag=useAdicionarPagamento(); const fechar=useFecharComanda(); const atualizar=useAtualizarComanda(); const removerPag=useRemoverPagamento(); const removerItem=useRemoverItemComanda(); const cancelar=useCancelarComanda();
  const [servicoId,setServicoId]=useState(""); const [produtoId,setProdutoId]=useState(""); const [forma,setForma]=useState("pix"); const [valor,setValor]=useState(""); const [desconto,setDesconto]=useState("0"); const [observacoes,setObservacoes]=useState("");
  useEffect(()=>{if(!atual)return;setDesconto(String(atual.desconto??0));setObservacoes(atual.observacoes??"");},[atual?.id,atual?.desconto,atual?.observacoes]);
  const pago=useMemo(()=>atual?.pagamentos?.reduce((s,p)=>s+Number(p.valor),0)??0,[atual]); const falta=Math.max(0,Number(atual?.total??0)-pago);
  if(!atual)return null;
  const editavel=atual.status==="aberta";
  async function addServico(){if(!servicoId)return;const s=servicos.find(x=>x.id===servicoId);if(!s)return;try{await addItem.mutateAsync({comanda_id:atual.id,tipo:"servico",servico_id:s.id,produto_id:null,descricao:s.nome,quantidade:1,valor_unitario:Number(s.preco)});setServicoId("");toast.success("Serviço adicionado.");}catch{toast.error("Não foi possível adicionar o serviço.");}}
  async function addProduto(){if(!produtoId)return;const p=produtos.find(x=>x.id===produtoId);if(!p)return;try{await addItem.mutateAsync({comanda_id:atual.id,tipo:"produto",produto_id:p.id,servico_id:null,descricao:p.nome,quantidade:1,valor_unitario:Number(p.preco_venda)});setProdutoId("");toast.success("Produto adicionado.");}catch{toast.error("Não foi possível adicionar o produto.");}}
  async function salvarAjustes(){try{await atualizar.mutateAsync({id:atual.id,desconto:Number(desconto||0),observacoes});toast.success("Desconto e observações salvos.");}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar.");}}
  async function pagamento(){const v=Number(valor||falta);if(v<=0){toast.error("Informe o valor.");return;}if(v>falta+0.009){toast.error("O pagamento não pode ultrapassar o valor restante.");return;}try{await addPag.mutateAsync({comandaId:atual.id,forma,valor:v});setValor("");toast.success("Pagamento registrado.");}catch{toast.error("Não foi possível registrar o pagamento.");}}
  async function concluir(){try{await fechar.mutateAsync(atual.id);toast.success("Atendimento finalizado e estoque atualizado.");onOpenChange(false);}catch(e){toast.error(e instanceof Error?e.message:"Confira os pagamentos antes de fechar.");}}
  async function cancelarAtual(){try{await cancelar.mutateAsync(atual.id);toast.success("Atendimento cancelado.");onOpenChange(false);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível cancelar.");}}
  return <Sheet open={Boolean(comanda)} onOpenChange={onOpenChange}><SheetContent side="bottom" className="max-h-[92vh] overflow-y-auto rounded-t-2xl sm:max-w-xl md:inset-y-0 md:right-0 md:left-auto md:h-full md:max-h-none md:rounded-none"><SheetHeader className="px-5 pt-5 text-left"><SheetTitle>{atual.clientes?.nome??"Atendimento"}</SheetTitle><SheetDescription>{atual.status==="fechada"?"Pagamento concluído.":atual.status==="cancelada"?"Atendimento cancelado.":"Adicione serviços, produtos, desconto e pagamentos."}</SheetDescription></SheetHeader><div className="space-y-5 px-5 pb-8 pt-3">
    <div className="space-y-2">{(atual.comanda_itens??[]).length===0?<p className="rounded-xl border border-dashed p-4 text-center text-sm text-muted-foreground">Nenhum item ainda.</p>:atual.comanda_itens?.map(i=><div key={i.id} className="flex items-center justify-between gap-3 rounded-xl border px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{i.descricao}</p><p className="text-xs text-muted-foreground">{Number(i.quantidade)} × {formatarMoeda(Number(i.valor_unitario))}</p></div><strong>{formatarMoeda(Number(i.total))}</strong>{editavel&&<Button size="icon" variant="ghost" className="size-8 rounded-lg text-destructive" onClick={()=>void removerItem.mutateAsync(i.id)}><Trash2 className="size-3.5"/></Button>}</div>)}</div>
    {editavel&&<div className="grid gap-2 sm:grid-cols-2"><div className="flex gap-2"><Select value={servicoId} onValueChange={setServicoId}><SelectTrigger className="h-11 flex-1 rounded-xl"><SelectValue placeholder="Serviço extra"/></SelectTrigger><SelectContent>{servicos.map(s=><SelectItem key={s.id} value={s.id}>{s.nome}</SelectItem>)}</SelectContent></Select><Button size="icon" variant="outline" className="size-11 rounded-xl" onClick={()=>void addServico()}><Plus className="size-4"/></Button></div><div className="flex gap-2"><Select value={produtoId} onValueChange={setProdutoId}><SelectTrigger className="h-11 flex-1 rounded-xl"><SelectValue placeholder="Produto"/></SelectTrigger><SelectContent>{produtos.filter(p=>p.ativo&&p.uso!=="interno").map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select><Button size="icon" variant="outline" className="size-11 rounded-xl" onClick={()=>void addProduto()}><Plus className="size-4"/></Button></div></div>}
    {editavel&&<div className="space-y-3 rounded-xl border p-3"><div className="grid grid-cols-[130px_1fr] items-end gap-3"><div className="space-y-2"><Label>Desconto (R$)</Label><Input type="number" min="0" max={Number(atual.subtotal)} step="0.01" className="h-11 rounded-xl" value={desconto} onChange={e=>setDesconto(e.target.value)}/></div><div className="space-y-2"><Label>Observações</Label><Input className="h-11 rounded-xl" value={observacoes} onChange={e=>setObservacoes(e.target.value)} placeholder="Opcional"/></div></div><Button size="sm" variant="outline" className="rounded-xl" onClick={()=>void salvarAjustes()}><Save className="size-3.5"/> Aplicar</Button></div>}
    <div className="rounded-xl bg-muted/50 p-4"><div className="flex justify-between text-sm"><span>Subtotal</span><span>{formatarMoeda(Number(atual.subtotal))}</span></div>{Number(atual.desconto)>0&&<div className="mt-1 flex justify-between text-sm text-success"><span>Desconto</span><span>- {formatarMoeda(Number(atual.desconto))}</span></div>}<div className="mt-2 flex justify-between text-lg font-semibold"><span>Total</span><span>{formatarMoeda(Number(atual.total))}</span></div><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>Pago</span><span>{formatarMoeda(pago)}</span></div></div>
    {editavel&&<div className="space-y-3"><Label>Registrar pagamento</Label><div className="grid grid-cols-[1fr_1fr_auto] gap-2"><Select value={forma} onValueChange={setForma}><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pix">PIX</SelectItem><SelectItem value="dinheiro">Dinheiro</SelectItem><SelectItem value="debito">Débito</SelectItem><SelectItem value="credito">Crédito</SelectItem><SelectItem value="outro">Outro</SelectItem></SelectContent></Select><Input type="number" step="0.01" min="0" className="h-11 rounded-xl" placeholder={falta.toFixed(2)} value={valor} onChange={e=>setValor(e.target.value)}/><Button className="h-11 rounded-xl" onClick={()=>void pagamento()}>Adicionar</Button></div>{atual.pagamentos?.map(p=><div key={p.id} className="flex items-center justify-between gap-2 rounded-xl border px-3 py-2 text-sm"><span className="capitalize">{p.forma_pagamento}</span><span className="ml-auto">{formatarMoeda(Number(p.valor))}</span><Button size="icon" variant="ghost" className="size-7 rounded-lg text-destructive" onClick={()=>void removerPag.mutateAsync(p.id)}><Trash2 className="size-3.5"/></Button></div>)}<Button className="h-12 w-full rounded-xl" disabled={falta>0.009||fechar.isPending||Number(atual.total)<=0} onClick={()=>void concluir()}><CheckCircle2 className="size-4"/>{falta>0.009?`Faltam ${formatarMoeda(falta)}`:"Fechar atendimento"}</Button>
      <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" className="h-11 w-full rounded-xl text-destructive"><XCircle className="size-4"/> Cancelar atendimento</Button></AlertDialogTrigger><AlertDialogContent className="rounded-2xl"><AlertDialogHeader><AlertDialogTitle>Cancelar este atendimento?</AlertDialogTitle><AlertDialogDescription>Os itens permanecem no histórico da comanda cancelada. Se houver pagamentos registrados, remova-os primeiro.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="rounded-xl">Voltar</AlertDialogCancel><AlertDialogAction className="rounded-xl" onClick={()=>void cancelarAtual()}>Cancelar atendimento</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    </div>}
  </div></SheetContent></Sheet>;
}
